### ISSUE TITLE
fig 1 中的部分模型提出时间

### ISSUE THREAD

**Issue by fangtaosong** [RUCAIBox/LLMSurvey#14]
PanGu-Σ 的提出时间应该是2023.3.20（但是fig 1 是2022.1-2022.3）？
![截屏2023-04-04 11 37 27](https://user-images.githubusercontent.com/59201842/229681118-52a6df99-5605-4e9d-8376-4b240f63ca0c.png)
![截屏2023-04-04 11 33 32](https://user-images.githubusercontent.com/59201842/229680563-96e57c94-9421-437a-b935-875361e75697.png)

**Comment by EliverQ** [comment]
谢谢您的反馈！我们已经注意到图里部分模型的时间和组织可能有些问题，将在这周进行统一修改。再次感谢！如果您有别的发现和建议也欢迎继续和我们联系。
