### ISSUE TITLE
How to get the Ratios of various data sources in the pre-training data?

### ISSUE THREAD

**Issue by jarheadjoe** [RUCAIBox/LLMSurvey#18]
How u get Ratios of various data sources in the pre-training data for existing LLMs in Fig2?
As for me, the data in the Fig2 differs from the paper I read.
For example, GPT-3 paper (https://arxiv.org/abs/2005.14165) did not mention conversation or code data. But in Fig2 GPT-3 used conversation and code data as pretrain data.
And for PaLM, the Proportion of data in Table 2(https://arxiv.org/pdf/2204.02311.pdf) was also different from your ratios.

<img width="454" alt="image" src="https://user-images.githubusercontent.com/21330284/231072325-15289043-8788-4ece-9bc9-b2c427419eaf.png">
<img width="149" alt="image" src="https://user-images.githubusercontent.com/21330284/231072508-c85f0d3e-0066-488b-8b77-fb9bdfa466d6.png">

**Comment by hyp1231** [comment]
Thanks so much for pointing out this issue! It seems that the bug was introduced while editing the raw figure file.

We will fix it, check all the other ratios again, and update our arXiv paper ASAP. Thanks again!

**Comment by Wangpeiyi9979** [comment]
Hello, how is the percentage of code data counted, is it the percentage of github data?

**Comment by hyp1231** [comment]
> Hello, how is the percentage of code data counted, is it the percentage of github data?

Yes. Typically, data collected from GitHub is categorized as "code".

**Comment by Wangpeiyi9979** [comment]
thanks
