### ISSUE TITLE
samples error?

### ISSUE THREAD

**Issue by xealml** [RUCAIBox/LLMSurvey#23]
in 4.3.1 Batch Training
Batch Training. For language model pre-training, existing work generally sets the batch size to a large number (e.g., 8,196 examples or 1.6M tokens)

maybe there are 8196*2048=16785408=16M tokens?

**Comment by EliverQ** [comment]
Thank you for bringing the typo to our attention. We will corrected it today. Please feel free to share any additional suggestions you may have.

**Comment by xealml** [comment]
> Could you please provide your name? We would like to include you in the acknowledgments for your correction.
Chinese name or what?  李孟霖 Or menglin Li
