### ISSUE TITLE
Some errors in Table 1

### ISSUE THREAD

**Issue by mzchtx** [RUCAIBox/LLMSurvey#24]
I think there might be some errors in Table 1.

1. The training resources(Tokens, Hardware and Training Time) for Baidu's ERNIE 3.0 are incorrect. The data is only estimated according to GPT-3 in the paper, not for ERNIE 3.0 Titan, as shown below.

![image](https://user-images.githubusercontent.com/37564754/236172065-343e1f66-14c3-4545-a3f4-a40746d3f4fd.png)

2. The training tokens for LaMDA are not 2.81T; that number represents the entire dataset. In actual training, 768B tokens were used, based on the paper's mention of 256K tokens per batch and a total of 3M steps, as shown below.
![image](https://user-images.githubusercontent.com/37564754/236172659-c70e679d-15ac-4ad2-b47f-f779be46f8fb.png)

**Comment by EliverQ** [comment]
Thank you for your correction. We will fix these errors in the upcoming version.

**Comment by EliverQ** [comment]
Could you please provide your name? We would like to include you in the acknowledgments for your correction.
