### ISSUE TITLE
About the grammar of "while"

### ISSUE THREAD

**Issue by ArkciaDragone** [RUCAIBox/LLMSurvey#30]
There are more than two dozen appearances of the conjunction "while" followed by a comma at the beginning of the sentence in the paper ("While,"). Every time I came upon the word, I expected an interrupter to follow, only to find none. I believe this usage is grammatically incorrect, and it becomes too painful to overlook as I read, since there are just too many of them. Please see [this link](https://www.scribbr.com/commas/comma-before-while/#after-while) for a detailed explanation.

A possible substitution for most of them, if not all, would be the word "however", which is often followed by a comma at the beginning of a sentence. It would be great if it could be corrected.

Besides, the word "sublayer" for Post Norm in Table 4 is misspelled as "su-layer-b".

**Comment by EliverQ** [comment]
Thank you for your correction! We indeed made grammar mistakes and will release an update after a major revision.
May we acknowledge you in our survey?  If you're willing, please leave your name.

**Comment by ArkciaDragone** [comment]
I'm so honored! "Yiting Liu" will do.

P.S. I just found that the formulas of LoRA used inconsistent letters (k and r) to represent the reduced rank. Maybe you would like to modify this as well.
