### ISSUE TITLE
Comments on paper

### ISSUE THREAD

**Issue by ToddMorrill** [RUCAIBox/LLMSurvey#31]
First - nicely done. This must have been a herculean effort to review all of these papers. Here are some ideas:

1. It would be nice to include more information about [Falcon](https://huggingface.co/blog/falcon) when their paper is released (still "coming soon" per [HF](https://huggingface.co/tiiuae/falcon-40b)). In particular, it seems that the creators of Falcon made a decision to use [multi-query attention](https://arxiv.org/abs/1911.02150) with an eye toward inference speed. It might nice to provide a little more detail about how different architecture choices (e.g. [attention mechanisms](https://arxiv.org/abs/2211.05102), etc.) impact tokens generated per second, which is what engineers and the [open source community](https://github.com/PanQiWei/AutoGPTQ) are very focused on (and quality of generation of course too). Tokens/second really impacts the user experience plus I would love to see how people are thinking about [truly enormous context sizes](https://arxiv.org/abs/2305.01625?utm_source=substack&utm_medium=email).
2. This is a small point and feel free to disregard it but the word "besides" has a certain usage pattern among native English speakers. It's commonly used as follows: make a claim about something in your first sentence, then say, "besides", and then make an even stronger claim that basically says, feel free to _disregard_ the first claim because here's an even _stronger_ claim. Here's an example: Tom would never survive life in the army; he's not tough enough. Besides, he's too old to be accepted. The point here is that every time you use "besides" in the paper, you undermine the strength of the sentence before "besides", which is not what you're trying to do. One final note is that "besides" is pretty colloquial and is seldom used in professional writing. What you're really looking for here are the following three linking phrases: also, in addition, and furthermore.

Again, thank you for your work here. There's so much happening in the LLM space so up-to-date reviews like this are really helpful.

**Comment by EliverQ** [comment]
Thanks for your suggestions! We'll add Falcon  in the upcoming update, and we will also gradually address the issue of "besides". We would like to include you in the acknowledgments. Could you please provide your name?

**Comment by ToddMorrill** [comment]
Sure, it's Todd Morrill.

**Comment by nmm5060** [comment]
> First - nicely done. This must have been a herculean effort to review all of these papers. Here are some ideas:
> 
> 
> 
> 1. It would be nice to include more information about [Falcon](https://huggingface.co/blog/falcon) when their paper is released (still "coming soon" per [HF](https://huggingface.co/tiiuae/falcon-40b)). In particular, it seems that the creators of Falcon made a decision to use [multi-query attention](https://arxiv.org/abs/1911.02150) with an eye toward inference speed. It might nice to provide a little more detail about how different architecture choices (e.g. [attention mechanisms](https://arxiv.org/abs/2211.05102), etc.) impact tokens generated per second, which is what engineers and the [open source community](https://github.com/PanQiWei/AutoGPTQ) are very focused on (and quality of generation of course too). Tokens/second really impacts the user experience plus I would love to see how people are thinking about [truly enormous context sizes](https://arxiv.org/abs/2305.01625?utm_source=substack&utm_medium=email).
> 
> 2. This is a small point and feel free to disregard it but the word "besides" has a certain usage pattern among native English speakers. It's commonly used as follows: make a claim about something in your first sentence, then say, "besides", and then make an even stronger claim that basically says, feel free to _disregard_ the first claim because here's an even _stronger_ claim. Here's an example: Tom would never survive life in the army; he's not tough enough. Besides, he's too old to be accepted. The point here is that every time you use "besides" in the paper, you undermine the strength of the sentence before "besides", which is not what you're trying to do. One final note is that "besides" is pretty colloquial and is seldom used in professional writing. What you're really looking for here are the following three linking phrases: also, in addition, and furthermore.
> 
> 
> 
> Again, thank you for your work here. There's so much happening in the LLM space so up-to-date reviews like this are really helpful.

Chaim
