### ISSUE TITLE
请教一个问题，在做指令问题的时候，验证集上计算损失和训练集是否一致

### ISSUE THREAD

**Issue by dazhaxie0526** [RUCAIBox/LLMSurvey#38]
基于基座模型比如LLaMA系列进行指令微调，训练的损失函数是什么？在验证集上计算损失跟训练集上是否一致，谢谢！

**Comment by EliverQ** [comment]
训练的损失函数需要看指令微调的具体任务，一般来说可能会是通用的自回归模型损失（交叉熵）；
在验证集上计算损失一般会比训练集大一些

**Comment by dazhaxie0526** [comment]
> 训练的损失函数需要看指令微调的具体任务，一般来说可能会是通用的自回归模型损失（交叉熵）； 在验证集上计算损失一般会比训练集大一些

好的，收到，多谢多谢
