### ISSUE TITLE
assets/LLM_Survey_Chinese_V1.pdf文件错误

### ISSUE THREAD

**Issue by raogj** [RUCAIBox/LLMSurvey#39]

**Comment by EliverQ** [comment]
请问您说的错误是指？我这边打开好像没有问题诶

**Comment by StevenTang1998** [comment]
已经修复了这个问题，非常感谢！

**Comment by raogj** [comment]
文件依旧打不开

**Comment by raogj** [comment]
是的
![image](https://github.com/RUCAIBox/LLMSurvey/assets/44366306/b9f31b84-a933-4ae9-ae09-9d6506e1603e)

**Comment by raogj** [comment]
下载后，打开时提示文件已损坏

**Comment by StevenTang1998** [comment]
![image](https://github.com/RUCAIBox/LLMSurvey/assets/37647985/22326bdc-31df-42c0-8a6c-ded9fbd8a2fe)
您好，我这里并没有这个问题，建议您更换网络、浏览器或者PDF阅读器。
