### ISSUE TITLE
咨询一下目前的中文版本是对应arxiv上的v几？

### ISSUE THREAD

**Issue by roki1031** [RUCAIBox/LLMSurvey#54]

**Comment by elmliu** [comment]
我也发现部分内容中文版没有英文版详细，比如标准化方法的部分

**Comment by EliverQ** [comment]
对应arxiv上的v4，因此有很多内容都没有更新，仅供参考，如果您想要更加详细的内容，建议您查看arxiv的最新版本~

**Comment by StevenTang1998** [comment]
我们的中文版对应的是英文版的v1，更新在英文版的内容我们会尽快在中文版同步
