### ISSUE TITLE
assets/LLM_Survey_Chinese.pdf 文件错误

### ISSUE THREAD

**Issue by code-bee** [RUCAIBox/LLMSurvey#59]
as title

**Comment by StevenTang1998** [comment]
![image](https://github.com/RUCAIBox/LLMSurvey/assets/37647985/c5539dd6-8997-4da1-8846-0030590fb382)

https://github.com/RUCAIBox/LLMSurvey/blob/main/assets/LLM_Survey_Chinese.pdf

我这里显示这样，请问您遇到了什么问题？

**Comment by code-bee** [comment]
可能是代理的问题，换了个网络，现在好了，抱歉
