### ISSUE TITLE
Add a new paper about LLMs as evaluators

### ISSUE THREAD

**Issue by Wangpeiyi9979** [RUCAIBox/LLMSurvey#63]
Thank you for your excellent survey.

Please consider adding our work: Large Language Models are not Fair Evaluators (https://arxiv.org/abs/2305.17926), to the list.

Our research has identified a positional bias while using LLMs as evaluators, and we have proposed three strategies to alleviate this bias.

Thanks.😊

**Comment by wxl1999** [comment]
Thanks for your suggested papers. We will consider adding your paper into the future version. For GitHub update, you may directly create a pull request into suitable part.

BTW, we have read your paper and find that it is also with the context of LLMs. We suggest you also discuss or cite our survey paper as a reference to the general introduction of LLMs.

**Comment by Wangpeiyi9979** [comment]
Thank you, we will ensure its inclusion in our upcoming revision.😊
