### ISSUE TITLE
Add a new Paper about Alignment Tuning

### ISSUE THREAD

**Issue by Wangpeiyi9979** [RUCAIBox/LLMSurvey#64]
Hi, thanks for your excellent survey.

We recently proposed a new alignment fine-tuning paradigm to enhance the reasoning ability of large language models.

Please consider adding our work to your repository and paper:
Title: Making Large Language Models Better Reasoners with Alignment
Link: https://arxiv.org/pdf/2309.02144.pdf

Thanks. 😊

**Comment by wxl1999** [comment]
Thanks for your suggested papers. We will consider adding your paper into the future version. For GitHub update, you may directly create a pull request into suitable part.

BTW, we have read your paper and find that it is also with the context of LLMs. We suggest you also discuss or cite our survey paper as a reference to the general introduction of LLMs.

**Comment by Wangpeiyi9979** [comment]
Thank you, we will ensure its inclusion in our upcoming revision.😊
