### ISSUE TITLE
Request for add  a new paper of medical LLM.

### ISSUE THREAD

**Issue by SupritYoung** [RUCAIBox/LLMSurvey#65]
Hi, thanks for your excellent survey.

We recently proposed a new open-source medical LLM (based on Ziya-LLaMA), and has also achieved a certain degree of influence.

Please consider adding our work to your repository and paper:
Title: Zhongjing: Enhancing the Chinese Medical Capabilities of Large Language Model through Expert Feedback and Real-world Multi-turn Dialogue
Github: https://github.com/SupritYoung/Zhongjing
Paper: https://arxiv.org/abs/2308.03549

Thanks. 😊

**Comment by StevenTang1998** [comment]
Thanks for your suggested papers. We will consider adding your paper into the future version. For GitHub update, you may directly create a pull request into suitable part.
