### ISSUE TITLE
中文综述无法下载

### ISSUE THREAD

**Issue by dlbrant** [RUCAIBox/LLMSurvey#72]
![image](https://github.com/RUCAIBox/LLMSurvey/assets/3113415/b0812c5d-26b9-4a5b-852d-f93f79fbe1a9)

**Comment by dlbrant** [comment]
点击下载也没反应

**Comment by EliverQ** [comment]
您好，可能是您那边的网络问题，我这里是可以正常下载的。

**Comment by xuanhuayang** [comment]
您好，中文无法下载
