### ISSUE TITLE
这都11月份了，这个项目已经2-3个月没有更新了。催更！！！

### ISSUE THREAD

**Issue by lizhixi212** [RUCAIBox/LLMSurvey#74]
这都11月份了，这个项目已经2-3个月没有更新了。催更！！！

**Comment by wxl1999** [comment]
您好，感谢您的持续关注！我们将在下周更新最新一版的综述及仓库！

**Comment by simonsjy** [comment]
催更+1 hhh

**Comment by StevenTang1998** [comment]
我们已经更新了第13版论文，欢迎关注：https://mp.weixin.qq.com/s/q0iCaUFT7HmjKmse0SptVA
