### ISSUE TITLE
What are the limitations of LLMs besides "hallucinations" ?

### ISSUE THREAD

**Issue by YuboFeng2023** [RUCAIBox/LLMSurvey#75]
Hi all,

Thank you for your efforts in conveying such a wonderful survey paper! 
I have followed your fabulous work from version 5 until now.
[Here is the link to my previous issues](https://github.com/RUCAIBox/LLMSurvey/issues/22)

I have a new question: **what are the other limitations of LLMs?**

Nowadays, there are overwhelming papers focusing on the "hallucination" of LLMs, but I wonder if LLMs have any other drawbacks.

When I searched for "hallucination" in your paper or explored the outlines, there was no section discussing the limitations of LLMs.

I believe that adding a "Limitations" section will enhance the paper!

Best wishes!

**Comment by turboLJY** [comment]
Thank you for your good suggestion. In section 7.1, we have also discussed several limitations of LLMs including hallucination. We will consider adding a specific ''Limitations'' section in the future.
