### ISSUE TITLE
There may be some errors in Figure 6

### ISSUE THREAD

**Issue by Asunatan** [RUCAIBox/LLMSurvey#83]
![error](https://github.com/RUCAIBox/LLMSurvey/assets/105210894/24e15795-4ee7-4761-8ec3-61b1268faecb)

**Comment by Asunatan** [comment]
![Uploading error.png…]()

**Comment by Asunatan** [comment]
![error](https://github.com/RUCAIBox/LLMSurvey/assets/105210894/39648b1e-8b1b-4544-bdeb-c9b2c2ab0019)

**Comment by hyp1231** [comment]
Hi, thanks for your interest in our paper! Could you please provide more details about the errors in the listed data source figures?

Take LLaMA as one example, we refer to the original [paper](https://arxiv.org/pdf/2302.13971.pdf), and categorize:
* (1) CommonCrawl (67%), C4 (15%), and Wikipedia (4.5%) as "Webpages" (86.5%),
* (2) GitHub (4.5%) as "Code" (4.5%),
* (3) Gutenberg and Books3 (4.5%) as "Books & News" (4.5%),
* (4) ArXiv (2.5%) as "Scientific Data" (2.5%), and
* (5) Stack Exchange (2%) as "Conversational Data" (2%).

**Comment by Asunatan** [comment]
Thank you very much for your answer. In the original LLaMA paper, the sources for the dataset are listed as follows: English CommonCrawl (67%), C4 (15%), Github (4.5%), Wikipedia (4.5%), Gutenberg and Books3 (4.5%), ArXiv (2.5%), and Stack Exchange (2%), adding up to a total of 100%. I'm confused as to why in Fig. 6 the sum is 102%.
