### ISSUE TITLE
关于LLMBook中对llama2模型参数量计算的疑问

### ISSUE THREAD

**Issue by minaduki-sora** [RUCAIBox/LLMSurvey#89]
![image](https://github.com/user-attachments/assets/8718f9f6-6003-4c12-b80f-cd2c8380fff6)
![image](https://github.com/user-attachments/assets/456a51ea-52ed-4aaa-9260-72dd414fc7b3)
为什么这里计算MHA参数时不考虑注意力头数呢？用H=ND去计算的话，每个注意力头的参数矩阵是N\*D\*D的参数量即H\*D，而书中则是H^2

**Comment by StevenTang1998** [comment]
正如你所说，每个注意力头的参数是H*D，N个注意力头的参数是N*H*D，即H^2

**Comment by minaduki-sora** [comment]
谢谢您的回答，不过每个注意力头的QKV矩阵参数应该是D\*D，刚刚我想错了，N个注意力头形成的模块才是N\*D\*D

**Comment by StevenTang1998** [comment]
不是的，每个注意力头的矩阵参数应该是N*D

**Comment by minaduki-sora** [comment]
非常感谢您！醍醐灌顶了，N\*D\*D拼接N个得到H*H的参数矩阵，从而实现并行化，之前就卡在这里没理解
