### ISSUE TITLE
v14 中 8.1.4 节MLLM结尾时突然改成了知识图谱，感觉突兀，是不是出错了？

### ISSUE THREAD

**Issue by twang2218** [RUCAIBox/LLMSurvey#90]
你好，我在阅读新版本 v14 的时候，阅读到 **8.1.4 Multimodal Large Language Model** 时，读到该小节文末，正在介绍MLLM的 *Safety and alignment* ，突然就画风一转，变成了介绍知识图谱Knowledge Graph的内容了。

![截屏2024-10-09 下午2 33 26](https://github.com/user-attachments/assets/e7b14ea1-e8e5-4e23-bba3-4a5f21418a4c)

感觉非常突兀。

我认为知识图谱KG应该是独立一小节，不应该是MLLM中的一部分，这里是不是在撰写和排版的时候不小心删除了一部分内容，导致了格式上的错误？

**Comment by Lancelot39** [comment]
Thank you very much for your constructive suggestion! It is indeed a typo when we compile the pdf file. We have fixed it and updated a new version in Arxiv.
