### ISSUE TITLE
关于86页公式(5.11)中O的shape

### ISSUE THREAD

**Issue by haozhi1817** [RUCAIBox/LLMSurvey#92]
书中提到：
![image](https://github.com/user-attachments/assets/8969ea8e-110d-4117-93d9-213c7f9c027e)
其中，V是目标词表的大小：
![image](https://github.com/user-attachments/assets/f2330f1d-e673-44f9-a5da-a6807ced4f9c)
H是词向量维度：
![image](https://github.com/user-attachments/assets/3a976304-cc0e-4f8f-8526-268af6afc99f)
我认为这里的O实际的shape应该是[N, V] ，其中N代表编码器输入的有效字符数（可见的前N个字符），O的shape与H没有任何关系。
退一万步讲，按照式(5.11) ，O的shape是[H,V]，W^L的shape是[H,V]，这意味着Y_L的shape是[V, V]，我不明白Y_L的shape怎么会是[V, V]？

**Comment by StevenTang1998** [comment]
非常感谢您指出我们的错误，O的shape如您所说应该是[T, V]，T在书中表示输入序列长度。
